#
# Module manifest for module 'PSComplexity'
#
# Generated by: Fortigi
#
# Generated on: 22/08/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSComplexity.psm1'

# Version number of this module.
ModuleVersion = '0.2.1'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = '961aa886-4f8e-40c0-9d25-68fd4c52e69f'

# Author of this module
Author = 'Fortigi'

# Company or vendor of this module
CompanyName = 'Fortigi'

# Copyright statement for this module
Copyright = '(c) Fortigi. MIT licensed.'

# Description of the functionality provided by this module
Description = 'Cyclomatic and cognitive complexity for PowerShell. Cognitive complexity is a faithful port of the SonarSource metric (nesting-aware -- the better signal for "hard to understand"), validated against reference scores. Measures per unit (function/filter, class method/constructor, initialised class property, + script body) via the PowerShell AST; ships a Test-PSComplexity gate for CI.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Measure-PSComplexity', 'Test-PSComplexity'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'complexity','cyclomatic','cognitive','code-quality','ast','metrics','maintainability','lint','ci'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Fortigi/PSComplexity/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Fortigi/PSComplexity'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '0.2.1: FIXED - this release fixes two separate ways the gate reported success without measuring anything, and if either affected you, your builds have been passing on evidence that was never gathered. First: scanning a DIRECTORY without -Recurse resolved to zero files. -Include is ignored for a directory unless -Recurse is also given, so Measure-PSComplexity ./src returned nothing for a folder full of code, and Test-PSComplexity ./src -MaxCyclomatic 1 returned $true against units that all breached. Second: a path containing [ or ] matched nothing, because -Path reads brackets as a wildcard character class, so a real directory named my[1]proj scored a confident, empty zero. Discovery now filters on the file extension and resolves an existing path literally; a pattern that names nothing on disk still falls through to wildcard matching, so ./src/*.ps1 keeps working. AND, so that neither can be silent again, Test-PSComplexity now THROWS when it measured no units instead of returning $true - nothing breached a ceiling and nothing was measured must never be the same answer. WHAT TO DO: if you gate a flat directory, re-run before upgrading and compare. A run that starts failing after this upgrade is the honest one. Full changelog: https://github.com/Fortigi/PSComplexity/blob/main/CHANGELOG.md'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

